<div style="background-color: white">
<div style="margin: auto; width: 70%; padding: 10px 0px 5px 70px">
    <img class="inline-block" src="../assets/IEE_logo.png">
    <span class="main-title"><a href="../page2.php" class="iee-home">Warehouse Milkrun</a>
        <span style="font-size: 0.5em; padding-left: 0;">v 1</span>
    </span>
</div>
</div>
<head>
   
    <title>Warehouse Milkrun v1</title>
    <link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../css/iee-common.css">
    <link rel="stylesheet" type="text/css" href="../css/magicsuggest.css">
    <link rel="stylesheet" type="text/css" href="../css/style.css?v=0.010">
    <script type="text/javascript" charset="utf-8" src="../js/jquery-3.2.0.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="../js/magicsuggest.js"></script>
    <script type="text/javascript" charset="utf-8" src="../js/ebapi-modules.js"></script>
    <script type="text/javascript" charset="utf-8" src="../js/pda.js?v=0.025"></script>
</head>
